# Change these first
owner: imZack # Your GitHub username
repo: up.zzz.dev # Your Github repository name

# Add your sites here
sites:
  - name: eit.tw
    url: https://eit.tw
  - name: Smokeping (zzz.dev)
    url: https://smokeping.zzz.dev/smokeping/
  - name: Travel Blog
    url: $URL_TRAVEL_BLOG
  - name: Tesla Dashboard
    url: $URL_TESLA_DASHBOARD

assignees:
  - imZack

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: up.zzz.dev
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: up.zzz.dev
  introTitle: "Uptime Monitor"
  introMessage: ""
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
